explore_node:
  # ros__parameters:
  #   robot_base_frame: base_link
  #   costmap_topic: /global_costmap/costmap
  #   costmap_updates_topic: /global_costmap/costmap_updates
  #   # costmap_topic: /map
  #   # costmap_updates_topic: /map_updates
  #   visualize: true
  #   planner_frequency: 0.1
  #   progress_timeout: 50.0
  #   potential_scale: 3.0
  #   orientation_scale: 0.0
  #   gain_scale: 1.0
  #   transform_tolerance: 0.5
  #   min_frontier_size: 0.60

  ros__parameters:
    robot_base_frame: base_link
    return_to_init: true
    # costmap_topic: /global_costmap/costmap
    # costmap_updates_topic: /global_costmap/costmap_updates
    costmap_topic: map
    costmap_updates_topic: map_updates
    visualize: true
    planner_frequency: 0.5
    progress_timeout: 30.0
    potential_scale: 3.0
    orientation_scale: 0.0
    gain_scale: 1.0
    transform_tolerance: 0.5
    min_frontier_size: 0.3